alter table THESISTEST_CUSTOMER add constraint FK_THESISTEST_CUSTOMER_USERS_ID foreign key (USERS_ID) references SEC_USER(ID);
create index IDX_THESISTEST_CUSTOMER_USERS on THESISTEST_CUSTOMER (USERS_ID);
