alter table DF_EMPLOYEE add constraint FK_DF_EMPLOYEE_SIGNER_CATEGORY_ID foreign key (SIGNER_CATEGORY_ID) references THESISTEST_SIGNERS(ID);
create index IDX_DF_EMPLOYEE_SIGNER_CATEGORY on DF_EMPLOYEE (SIGNER_CATEGORY_ID);
