alter table DF_MEETING_DOC add constraint FK_DF_MEETING_DOC_SIGNED_BY_WHOM_ID foreign key (SIGNED_BY_WHOM_ID) references DF_EMPLOYEE(CORRESPONDENT_ID);
create index IDX_DF_MEETING_DOC_SIGNED_BY_WHOM on DF_MEETING_DOC (SIGNED_BY_WHOM_ID);
