-- begin THESISTEST_ORDER
alter table THESISTEST_ORDER add constraint FK_THESISTEST_ORDER_CUSTOMER_ID foreign key (CUSTOMER_ID) references THESISTEST_CUSTOMER(ID)^
create index IDX_THESISTEST_ORDER_CUSTOMER on THESISTEST_ORDER (CUSTOMER_ID)^
-- end THESISTEST_ORDER
-- begin THESISTEST_CUSTOMER
alter table THESISTEST_CUSTOMER add constraint FK_THESISTEST_CUSTOMER_USERS_ID foreign key (USERS_ID) references SEC_USER(ID)^
create index IDX_THESISTEST_CUSTOMER_USERS on THESISTEST_CUSTOMER (USERS_ID)^
-- end THESISTEST_CUSTOMER
-- begin DF_CONTRACT
alter table DF_CONTRACT add constraint FK_DF_CONTRACT_CUSTOMER_ID foreign key (CUSTOMER_ID) references THESISTEST_CUSTOMER(ID)^
create index IDX_DF_CONTRACT_CUSTOMER on DF_CONTRACT (CUSTOMER_ID)^
alter table DF_CONTRACT add constraint FK_DF_CONTRACT_ORDER_ID foreign key (ORDER_ID) references THESISTEST_ORDER(ID)^
create index IDX_DF_CONTRACT_ORDER on DF_CONTRACT (ORDER_ID)^
-- end DF_CONTRACT
-- begin DF_EMPLOYEE
alter table DF_EMPLOYEE add constraint FK_DF_EMPLOYEE_SIGNER_CATEGORY_ID foreign key (SIGNER_CATEGORY_ID) references THESISTEST_SIGNERS(ID)^
create index IDX_DF_EMPLOYEE_SIGNER_CATEGORY on DF_EMPLOYEE (SIGNER_CATEGORY_ID)^
-- end DF_EMPLOYEE

-- begin DF_SIMPLE_DOC
alter table DF_SIMPLE_DOC add constraint FK_DF_SIMPLE_DOC_DOC_CARD_ID foreign key (DOC_CARD_ID) references THESISTEST_CATEGORIES(ID)^
create index IDX_DF_SIMPLE_DOC_DOC_CARD on DF_SIMPLE_DOC (DOC_CARD_ID)^
alter table DF_SIMPLE_DOC add constraint FK_DF_SIMPLE_DOC_NEW_SIGNED_BY_ID foreign key (NEW_SIGNED_BY_ID) references DF_EMPLOYEE(CORRESPONDENT_ID)^
create index IDX_DF_SIMPLE_DOC_NEW_SIGNED_BY on DF_SIMPLE_DOC (NEW_SIGNED_BY_ID)^
-- end DF_SIMPLE_DOC
