-- begin THESISTEST_ORDER
alter table THESISTEST_ORDER add constraint FK_THESISTEST_ORDER_CUSTOMER_ID foreign key (CUSTOMER_ID) references THESISTEST_CUSTOMER(ID)^
create index IDX_THESISTEST_ORDER_CUSTOMER on THESISTEST_ORDER (CUSTOMER_ID)^
-- end THESISTEST_ORDER
-- begin THESISTEST_CUSTOMER
alter table THESISTEST_CUSTOMER add constraint FK_THESISTEST_CUSTOMER_USERS_ID foreign key (USERS_ID) references SEC_USER(ID)^
create index IDX_THESISTEST_CUSTOMER_USERS on THESISTEST_CUSTOMER (USERS_ID)^
-- end THESISTEST_CUSTOMER
